version: '3.3'

services:
  chat-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: chat/client
    command: node server.js
    ports:
      - '5008:8080'
  chat-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: chat/server
    command: bash -c "forever --watch src/index.js"
    ports:
      - '5006:3000'
    